"""Aggiunto tipo ufficializzazione

Revision ID: 0214cd627299
Revises: e4557ff6dcf1
Create Date: 2026-04-03 11:10:48.274548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0214cd627299'
down_revision = 'e4557ff6dcf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impegni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_ufficializzazione', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impegni', schema=None) as batch_op:
        batch_op.drop_column('tipo_ufficializzazione')

    # ### end Alembic commands ###
