"""Creazione tabelle PSN e Impegni

Revision ID: 76d010fc31b9
Revises: 
Create Date: 2026-04-01 12:42:13.455301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d010fc31b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impegni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('titolo', sa.String(length=255), nullable=False),
    sa.Column('costo_previsto', sa.Float(), nullable=True),
    sa.Column('data_determina', sa.Date(), nullable=True),
    sa.Column('num_determina', sa.String(length=50), nullable=True),
    sa.Column('costo_determina', sa.Float(), nullable=True),
    sa.Column('pagamenti_effettuati', sa.Float(), nullable=True),
    sa.Column('stato_logico', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progetti_psn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anno_assegnazione', sa.Integer(), nullable=False),
    sa.Column('anno_riferimento', sa.Integer(), nullable=False),
    sa.Column('conti_aziendali', sa.String(length=255), nullable=True),
    sa.Column('azioni', sa.Text(), nullable=True),
    sa.Column('referenti', sa.String(length=255), nullable=True),
    sa.Column('quota_assegnata', sa.Float(), nullable=True),
    sa.Column('stato', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assegnazioni_impegni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('impegno_id', sa.Integer(), nullable=False),
    sa.Column('progetto_id', sa.Integer(), nullable=False),
    sa.Column('costo_assegnato', sa.Float(), nullable=False),
    sa.Column('data_creazione', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['impegno_id'], ['impegni.id'], ),
    sa.ForeignKeyConstraint(['progetto_id'], ['progetti_psn.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assegnazioni_impegni')
    op.drop_table('progetti_psn')
    op.drop_table('impegni')
    # ### end Alembic commands ###
