"""Aggiunti campi note e iter determina a Impegni

Revision ID: 92bb9a032764
Revises: 76d010fc31b9
Create Date: 2026-04-01 19:38:18.634066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92bb9a032764'
down_revision = '76d010fc31b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impegni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_nota', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_nota', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impegni', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('data_nota')
        batch_op.drop_column('numero_nota')

    # ### end Alembic commands ###
