"""Aggiunta disp comunicata in Progetti

Revision ID: d17be78da373
Revises: 0214cd627299
Create Date: 2026-04-03 12:06:41.132522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17be78da373'
down_revision = '0214cd627299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progetti_psn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disp_comunicata', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('data_disp_comunicata', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progetti_psn', schema=None) as batch_op:
        batch_op.drop_column('data_disp_comunicata')
        batch_op.drop_column('disp_comunicata')

    # ### end Alembic commands ###
