"""Aggiunta tabella Note PSN

Revision ID: e4557ff6dcf1
Revises: f60152319c51
Create Date: 2026-04-03 10:47:40.298006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4557ff6dcf1'
down_revision = 'f60152319c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_psn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progetto_id', sa.Integer(), nullable=False),
    sa.Column('testo', sa.Text(), nullable=False),
    sa.Column('importante', sa.Boolean(), nullable=True),
    sa.Column('data_creazione', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['progetto_id'], ['progetti_psn.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_psn')
    # ### end Alembic commands ###
