"""Aggiunto storico a assegnazione

Revision ID: f60152319c51
Revises: 92bb9a032764
Create Date: 2026-04-01 19:46:51.033952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60152319c51'
down_revision = '92bb9a032764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assegnazioni_impegni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storico', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assegnazioni_impegni', schema=None) as batch_op:
        batch_op.drop_column('storico')

    # ### end Alembic commands ###
